name: agora_uikit
description: Flutter plugin to simply integrate Agora Video Calling or Live
  Video Streaming to your app with just a few lines of code.
version: 1.3.10
homepage: https://www.agora.io/en/
repository: https://github.com/AgoraIO-Community/VideoUIKit-Flutter
publish_to: none  # This prevents the package from being published


environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=2.2.0"

dependencies:
#  agora_rtc_engine:
#    git:
#      url: https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK.git
#      ref: main # branch name
  agora_rtc_engine: ^6.5.0
#  agora_rtc_engine:
#    path: ../Agora-Flutter-SDK
  flutter:
    sdk: flutter
  http: ">=0.13.1 <2.0.0"
  lints: ">=1.0.1 <3.0.1"
  permission_handler: ^11.0.0
#  agora_rtm: 2.2.2
#  agora_rtm:
#    git:
#      url: https://github.com/AgoraIO-Extensions/Agora-Flutter-RTM-SDK
#      ref: 1.5.9-NewUI

  agora_rtm:
    git:
      url: https://github.com/rehan-505/Agora-Flutter-RTM-SDK.git
      ref: 1.5.9-NewUI

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.agora.agora_uikit
        pluginClass: AgoraUikitPlugin
      ios:
        pluginClass: AgoraUikitPlugin

analyzer:
  strong-mode: true
  errors:
    mixin_inherits_from_not_object: ignore
